In [10]:
import pandas as pd
import numpy as np

In [2]:
tips=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/tips.csv')

In [3]:
wine_quality=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/winequalityN.csv')

In [4]:
titanic=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/titanic.csv' \
'')

In [5]:
amazon=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv',encoding='ISO-8859-1')

In [6]:
hr=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')

In [13]:
print('rows:',tips.shape[0])

rows: 244

In [14]:
print('columns:',tips.shape[1])

columns: 8

In [17]:
print(tips.head(5))
print(amazon.head(5))
print(hr.head(5))
print(wine_quality.head(5))
print(titanic.head(5))

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4
    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002
   employee_id  number_project  average_montly_hours  time_spend_company  \
0         1003               2                   157                   3
1         1005               5                   262                   6
2         1486               7                   272                   4
3         1038               5                   223                   5
4         1057               2                   159                   3

   Work_accident  left  promotion_last_5years department  salary
0              0     1                      0      sales     low
1              0     1                      0      sales  medium
2              0     1                      0      sales  medium
3              0     1                      0      sales     low
4              0     1                      0      sales     low
    type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0  white            7.0              0.27         0.36            20.7
1  white            6.3              0.30         0.34             1.6
2  white            8.1              0.28         0.40             6.9
3  white            7.2              0.23         0.32             8.5
4  white            7.2              0.23         0.32             8.5

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00
1      0.049                 14.0                 132.0   0.9940  3.30
2      0.050                 30.0                  97.0   0.9951  3.26
3      0.058                 47.0                 186.0   0.9956  3.19
4      0.058                 47.0                 186.0   0.9956  3.19

   sulphates  alcohol  quality
0       0.45      8.8        6
1       0.49      9.5        6
2       0.44     10.1        6
3       0.40      9.9        6
4       0.40      9.9        6
   pclass                                             name     sex      age  \
0       1                    Allen, Miss. Elisabeth Walton  female  29.0000
1       1                   Allison, Master. Hudson Trevor    male   0.9167
2       1                     Allison, Miss. Helen Loraine  female   2.0000
3       1             Allison, Mr. Hudson Joshua Creighton    male  30.0000
4       1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0000

   sibsp  parch  ticket      fare    cabin embarked  survived
0      0      0   24160  211.3375       B5        S         1
1      1      2  113781  151.5500  C22 C26        S         1
2      1      2  113781  151.5500  C22 C26        S         0
3      1      2  113781  151.5500  C22 C26        S         0
4      1      2  113781  151.5500  C22 C26        S         0

In [18]:
tips.columns

Index(['Unnamed: 0', 'total_bill', 'tip', 'sex', 'smoker', 'day', 'time',
       'size'],
      dtype='str')

In [19]:
tips.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  244 non-null    int64
 1   total_bill  244 non-null    float64
 2   tip         244 non-null    float64
 3   sex         244 non-null    str
 4   smoker      244 non-null    str
 5   day         244 non-null    str
 6   time        244 non-null    str
 7   size        244 non-null    int64
dtypes: float64(2), int64(2), str(4)
memory usage: 15.4 KB

In [20]:
hr.info()

<class 'pandas.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   employee_id            14999 non-null  int64
 1   number_project         14999 non-null  int64
 2   average_montly_hours   14999 non-null  int64
 3   time_spend_company     14999 non-null  int64
 4   Work_accident          14999 non-null  int64
 5   left                   14999 non-null  int64
 6   promotion_last_5years  14999 non-null  int64
 7   department             14999 non-null  str
 8   salary                 14999 non-null  str
dtypes: int64(7), str(2)
memory usage: 1.0 MB

In [21]:
def summary(df):
    print(df.info())

summary(tips)

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  244 non-null    int64
 1   total_bill  244 non-null    float64
 2   tip         244 non-null    float64
 3   sex         244 non-null    str
 4   smoker      244 non-null    str
 5   day         244 non-null    str
 6   time        244 non-null    str
 7   size        244 non-null    int64
dtypes: float64(2), int64(2), str(4)
memory usage: 15.4 KB
None

In [28]:
lst=[tips.shape[1], amazon.shape[1], hr.shape[1], wine_quality.shape[1], titanic.shape[1]]


x=np.array(lst)


np.max(x)

np.int64(13)

In [33]:
l=[1,2,3,4,5]
pd.Series(l,name='numbers',index=['a','b','c','d','e'])

a    1
b    2
c    3
d    4
e    5
Name: numbers, dtype: int64

In [37]:
d={'ENAME':['SMITH','ALLEN','WARD','JONES','MARTIN','BLAKE','CLARK','SCOTT','KING','TURNER'],
   'JOB':['CLERK','SALESMAN','SALESMAN','MANAGER','SALESMAN','MANAGER','MANAGER','ANALYST','PRESIDENT','SALESMAN'],
   'MGR':[7902,7698,7698,7839,7698,7839,7839,7566,7839,7698],
   'HIREDATE':['17-DEC-80','20-FEB-81','22-FEB-81','02-APR-81','28-SEP-81','01-MAY-81','09-JUN-81','19-APR-87','17-NOV-81','08-SEP-81'],
   'SAL':[800,1600,1250,2975,1250,2850,2450,3000,5000,1500],
   'COMM':[None,300,None,None,1400,None,None,None,None,-100],
   'DEPTNO':[20,30,30,20,30,30,10,20,10,30]}

In [38]:
df=pd.DataFrame(d)

In [39]:
df

    ENAME        JOB   MGR   HIREDATE   SAL    COMM  DEPTNO
0   SMITH      CLERK  7902  17-DEC-80   800     NaN      20
1   ALLEN   SALESMAN  7698  20-FEB-81  1600   300.0      30
2    WARD   SALESMAN  7698  22-FEB-81  1250     NaN      30
3   JONES    MANAGER  7839  02-APR-81  2975     NaN      20
4  MARTIN   SALESMAN  7698  28-SEP-81  1250  1400.0      30
5   BLAKE    MANAGER  7839  01-MAY-81  2850     NaN      30
6   CLARK    MANAGER  7839  09-JUN-81  2450     NaN      10
7   SCOTT    ANALYST  7566  19-APR-87  3000     NaN      20
8    KING  PRESIDENT  7839  17-NOV-81  5000     NaN      10
9  TURNER   SALESMAN  7698  08-SEP-81  1500  -100.0      30

In [41]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [43]:
titanic.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [46]:
titanic[['name','age','sex']]

                                                 name      age     sex
0                       Allen, Miss. Elisabeth Walton  29.0000  female
1                      Allison, Master. Hudson Trevor   0.9167    male
2                        Allison, Miss. Helen Loraine   2.0000  female
3                Allison, Mr. Hudson Joshua Creighton  30.0000    male
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0000  female
...                                               ...      ...     ...
1304                             Zabour, Miss. Hileni  14.5000  female
1305                            Zabour, Miss. Thamine      NaN  female
1306                        Zakarian, Mr. Mapriededer  26.5000    male
1307                              Zakarian, Mr. Ortin  27.0000    male
1308                               Zimmerman, Mr. Leo  29.0000    male

[1309 rows x 3 columns]

In [47]:
titanic.loc[0:5,['name','age','sex']]

                                              name      age     sex
0                    Allen, Miss. Elisabeth Walton  29.0000  female
1                   Allison, Master. Hudson Trevor   0.9167    male
2                     Allison, Miss. Helen Loraine   2.0000  female
3             Allison, Mr. Hudson Joshua Creighton  30.0000    male
4  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  25.0000  female
5                              Anderson, Mr. Harry  48.0000    male