In [1]:
import pandas as pd
import numpy as np

In [23]:
e={'data':['r','a','s','t','m','n'],'random':[0,1,0,1,0,1],'python':['p','y','t','h','o','n']}
n=['p','s','t','a','a','b']

f={'Buda':['r','a','s','t','a','r'],'Paris':[1,1,1,1,1,1],'python':['p','y','t','h','o','n'],'london':['l','o','n','d','o','n']}

In [24]:
a=pd.DataFrame(e)
b=pd.DataFrame(f)

In [4]:
a.loc[:,['data','random','python']]

  data  random python
0    r       0      p
1    a       1      y
2    s       0      t
3    t       1      h
4    m       0      o
5    n       1      n

In [5]:
a.iloc[:,[0,1,2]]

  data  random python
0    r       0      p
1    a       1      y
2    s       0      t
3    t       1      h
4    m       0      o
5    n       1      n

In [6]:
d={'data':'Data','random':'Random','python':'Python'}
a=a.rename(columns=d)

In [7]:
a

  Data  Random Python
0    r       0      p
1    a       1      y
2    s       0      t
3    t       1      h
4    m       0      o
5    n       1      n

In [8]:
a['Random']=a['Random'].astype(str)

In [9]:
d={'0':'2','1':'4'}

a['Random']=a['Random'].map(d)

In [10]:
a

  Data Random Python
0    r      2      p
1    a      4      y
2    s      2      t
3    t      4      h
4    m      2      o
5    n      4      n

In [17]:
a

  data  random python
0    r       0      p
1    a       1      y
2    s       0      t
3    t       1      h
4    m       0      o
5    n       1      n

In [18]:
b

  Buda  Paris python
0    r      1      p
1    a      1      y
2    s      1      t
3    t      1      h
4    a      1      o
5    r      1      n

In [26]:
pd.merge(a,b,how='right')

  data  random python Buda  Paris london
0    r       0      p    r      1      l
1    a       1      y    a      1      o
2    s       0      t    s      1      n
3    t       1      h    t      1      d
4    m       0      o    a      1      o
5    n       1      n    r      1      n

In [29]:
pd.concat([a,b],axis=1)

  data  random python Buda  Paris python london
0    r       0      p    r      1      p      l
1    a       1      y    a      1      y      o
2    s       0      t    s      1      t      n
3    t       1      h    t      1      h      d
4    m       0      o    a      1      o      o
5    n       1      n    r      1      n      n

In [30]:
wine_quality=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/winequalityN.csv')

In [31]:
wine_quality.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [ ]:
pd.pivot_table(wine_quality,)