In [3]:
import numpy as np

In [2]:
import pandas as pd

In [24]:
appliances=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/uncleaned_appliances.csv')

titanic=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/titanic.csv'
'')
wine_quality=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/winequalityN.csv')

tips=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/tips.csv')

amazon=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv',encoding='ISO-8859-1')

hr=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')

KeyboardInterrupt:

In [4]:
appliances=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/uncleaned_appliances.csv')

In [ ]:
appliances.head()

,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,goods-title-link
0,1pc Rechargeable Deep Tissue Muscle Handheld M...,https://us.shein.com/1pc-Rechargeable-Deep-Tis...,#1 Best Sellers,in Give Gifts,$2.03,-22%,NaN,NaN
1,1pc Portable Hanging Neck Fan,https://us.shein.com/1pc-Portable-Hanging-Neck...,#4 Best Sellers,in Top rated in Portable Fans,$6.48,-20%,NaN,NaN
2,1pc Pink Colored Curved Eyelash Curler False E...,https://us.shein.com/1pc-Pink-Colored-Curved-E...,NaN,NaN,$1.80,NaN,400+ sold recently,NaN
3,1 Mini Portable Handheld Fan With 2 Aa Batteri...,https://us.shein.com/1-Mini-Portable-Handheld-...,NaN,NaN,$0.88,-72%,5.6k+ sold recently,NaN
4,"Wit Water Flosser,Portable Oral Irrigator With...",https://us.shein.com/Wit-Water-Flosser-Portabl...,#6 Best Sellers,in Oral Irrigators,$12.06,-40%,NaN,NaN

In [5]:
appliances['rank-sub'].unique()

<StringArray>
[                           'in Give Gifts',
            'in Top rated in Portable Fans',
                                        nan,
                       'in Oral Irrigators',
              'in Refrigerators & Freezers',
            'in Other Household Appliances',
                  'in Oral Care Appliances',
                  'in Household Appliances',
 'in Women Shave & Hair Removal Appliances',
                   'in Vacuum Food Sealers',
 ...
             'in Portable Washing Machines',
               'in Water Filter Cartridges',
                         'in Meat Grinders',
                     'in Electric Blankets',
                      'in Washing Machines',
                          'in Stand Mixers',
                      'in Major Appliances',
                         'in Massage Chair',
                      'in Warming Products',
                            'in Hot Plates']
Length: 125, dtype: str

In [ ]:
appliances.head(
    
)

,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,goods-title-link
0,1pc Rechargeable Deep Tissue Muscle Handheld M...,https://us.shein.com/1pc-Rechargeable-Deep-Tis...,#1 Best Sellers,Give Gifts,$2.03,-22%,NaN,NaN
1,1pc Portable Hanging Neck Fan,https://us.shein.com/1pc-Portable-Hanging-Neck...,#4 Best Sellers,Top rated in Portable Fans,$6.48,-20%,NaN,NaN
2,1pc Pink Colored Curved Eyelash Curler False E...,https://us.shein.com/1pc-Pink-Colored-Curved-E...,NaN,NaN,$1.80,NaN,400+ sold recently,NaN
3,1 Mini Portable Handheld Fan With 2 Aa Batteri...,https://us.shein.com/1-Mini-Portable-Handheld-...,NaN,NaN,$0.88,-72%,5.6k+ sold recently,NaN
4,"Wit Water Flosser,Portable Oral Irrigator With...",https://us.shein.com/Wit-Water-Flosser-Portabl...,#6 Best Sellers,Oral Irrigators,$12.06,-40%,NaN,NaN

In [6]:
appliances.drop(['rank-sub','goods-title-link--jump','goods-title-link--jump href',
              'goods-title-link'],inplace=True, axis=1)

In [7]:
appliances.head()

        rank-title   price discount  selling_proposition
0  #1 Best Sellers   $2.03     -22%                  NaN
1  #4 Best Sellers   $6.48     -20%                  NaN
2              NaN   $1.80      NaN   400+ sold recently
3              NaN   $0.88     -72%  5.6k+ sold recently
4  #6 Best Sellers  $12.06     -40%                  NaN

In [8]:
appliances['price'].unique()

<StringArray>
[    '$2.03',     '$6.48',     '$1.80',     '$0.88',    '$12.06',     '$2.70',
     '$3.50',     '$4.90',     '$4.28',     '$2.76',
 ...
   '$240.00',    '$70.00',    '$73.97',    '$92.39',   '$326.85',    '$61.56',
 '$1,399.99',    '$60.47', '$1,499.99',    '$54.34']
Length: 1512, dtype: str

In [9]:
appliances['price']=appliances['price'].str.strip('$')
appliances['price']=appliances['price'].str.replace(',','')

In [10]:
appliances['price'].unique()

<StringArray>
[   '2.03',    '6.48',    '1.80',    '0.88',   '12.06',    '2.70',    '3.50',
    '4.90',    '4.28',    '2.76',
 ...
  '240.00',   '70.00',   '73.97',   '92.39',  '326.85',   '61.56', '1399.99',
   '60.47', '1499.99',   '54.34']
Length: 1512, dtype: str

In [11]:
appliances['price']=appliances['price'].astype(float)

In [17]:
out=[]

for i in appliances['price']:
    out.append(' ₹'+str(i*95))

In [18]:
appliances['price']=out

In [19]:
appliances.head()

,rank-title,price,discount,selling_proposition
0,#1 Best Sellers,₹ ₹2.03 ₹2.03 ₹2.03 ₹2.03 ₹2.03 ₹2.03 ₹2.03 ₹...,-22%,NaN
1,#4 Best Sellers,₹ ₹6.48 ₹6.48 ₹6.48 ₹6.48 ₹6.48 ₹6.48 ₹6.48 ₹...,-20%,NaN
2,NaN,₹ ₹1.8 ₹1.8 ₹1.8 ₹1.8 ₹1.8 ₹1.8 ₹1.8 ₹1.8 ₹1....,NaN,400+ sold recently
3,NaN,₹ ₹0.88 ₹0.88 ₹0.88 ₹0.88 ₹0.88 ₹0.88 ₹0.88 ₹...,-72%,5.6k+ sold recently
4,#6 Best Sellers,₹ ₹12.06 ₹12.06 ₹12.06 ₹12.06 ₹12.06 ₹12.06 ₹...,-40%,NaN

In [22]:
# groupby
# When we want to split the data into groups we use groupby function.

# var_1=var.groupby('categorized_column')

# var_1.groups()

# var_1.get_group('group_name')

In [25]:
wine_quality=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/winequalityN.csv')

In [26]:
wine_quality['type'].unique()

<StringArray>
['white', 'red']
Length: 2, dtype: str

In [27]:
wine_groups=wine_quality.groupby('type')

In [29]:
wine_groups.groups

{'red': [4898, 4899, 4900, 4901, 4902, 4903, 4904, 4905, 4906, 4907, 4908, 4909, 4910, 4911, 4912, 4913, 4914, 4915, 4916, 4917, 4918, 4919, 4920, 4921, 4922, 4923, 4924, 4925, 4926, 4927, 4928, 4929, 4930, 4931, 4932, 4933, 4934, 4935, 4936, 4937, 4938, 4939, 4940, 4941, 4942, 4943, 4944, 4945, 4946, 4947, 4948, 4949, 4950, 4951, 4952, 4953, 4954, 4955, 4956, 4957, 4958, 4959, 4960, 4961, 4962, 4963, 4964, 4965, 4966, 4967, 4968, 4969, 4970, 4971, 4972, 4973, 4974, 4975, 4976, 4977, 4978, 4979, 4980, 4981, 4982, 4983, 4984, 4985, 4986, 4987, 4988, 4989, 4990, 4991, 4992, 4993, 4994, 4995, 4996, 4997, ...], 'white': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]}

In [30]:
wine_groups.get_group('red')

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
4898,red,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
4899,red,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
4900,red,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
4901,red,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4902,red,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,red,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,NaN,11.2,6
6494,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [31]:
hr=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')

In [32]:
hr.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [35]:
dept=hr.groupby('department')

In [38]:
s=dept.get_group('sales')

In [39]:
s

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14967,87507,2,128,3,0,1,0,sales,low
14968,87518,2,128,3,0,1,0,sales,medium
14969,87520,2,157,3,0,1,0,sales,medium
14970,87530,4,225,5,0,1,0,sales,medium
14971,87533,2,140,3,0,1,0,sales,medium

In [40]:
s['employee_id'].count()

np.int64(4140)

In [51]:
it=dept.get_group('IT')

In [43]:
it['employee_id'].count()

np.int64(1227)

In [65]:
left=dept.get_group('IT')['left'].sum()

In [66]:
left

np.int64(273)

In [61]:
avg_RnD=dept.get_group('RandD')['number_project'].mean()

In [62]:
avg_RnD

np.float64(3.8538754764930117)

In [67]:
no_of_emp=dept.get_group('hr')['employee_id'].count()

In [68]:
no_of_emp

np.int64(739)