In [2]:
import pandas as pd
import numpy as np

In [3]:
titanic=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/titanic.csv'
'')

In [4]:
titanic['surname']=titanic['name'].str.split(',').str[0]

In [6]:
titanic.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,surname
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1,Allen
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1,Allison
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0,Allison
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0,Allison
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0,Allison

In [9]:
titanic['prefix']=titanic['name'].str.split('.').str[0]

In [16]:
titles = []

for i in titanic['prefix']:
    parts = str(i).split(',')

    if len(parts) > 1:
        titles.append(parts[1].strip())
    else:
        titles.append(parts[0].strip())

titanic['prefix'] = titles

In [17]:
titanic.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,surname,prefix
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1,Allen,Miss
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1,Allison,Master
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0,Allison,Miss
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0,Allison,Mr
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0,Allison,Mrs

In [24]:
tips=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/tips.csv')

In [28]:
tips['total_bills']=tips['total_bill']+tips['tip']

In [29]:
tips.head()

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size  total_bills
0           0       16.99  1.01  Female     No  Sun  Dinner     2        18.00
1           1       10.34  1.66    Male     No  Sun  Dinner     3        12.00
2           2       21.01  3.50    Male     No  Sun  Dinner     3        24.51
3           3       23.68  3.31    Male     No  Sun  Dinner     2        26.99
4           4       24.59  3.61  Female     No  Sun  Dinner     4        28.20

In [30]:
# pivot table:
# It is called as power house of pandas.
# It is used to apply multiple aggregation functions on multiple columns at the same time.

# Syntax: 
# var.pivot_table(values=['col1','col2',...]
#                 index='categorical_column',
#                 aggfunc=['fname_1','fname_2',,,])

In [31]:
wine_quality=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/winequalityN.csv')

In [32]:
wine_quality.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [33]:
wine_quality.pivot_table(values=['pH','quality','alcohol'],
                         index='type',
                         aggfunc=['mean','sum','max'])

            mean                           sum                       max  \
         alcohol        pH   quality   alcohol        pH quality alcohol
type
red    10.422983  3.310864  5.636023  16666.35   5287.45    9012    14.9
white  10.514267  3.188203  5.877909  51498.88  15593.50   28790    14.2


         pH quality
type
red    4.01       8
white  3.82       9

In [34]:
tips.head()

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size  total_bills
0           0       16.99  1.01  Female     No  Sun  Dinner     2        18.00
1           1       10.34  1.66    Male     No  Sun  Dinner     3        12.00
2           2       21.01  3.50    Male     No  Sun  Dinner     3        24.51
3           3       23.68  3.31    Male     No  Sun  Dinner     2        26.99
4           4       24.59  3.61  Female     No  Sun  Dinner     4        28.20

In [35]:
tips.pivot_table(values=['total_bill','total_bills','size'],
                 index='sex',
                 aggfunc=['max','mean'])

        max                             mean
       size total_bill total_bills      size total_bill total_bills
sex
Female    6      44.30       48.11  2.459770  18.056897   20.890345
Male      6      50.81       60.81  2.630573  20.744076   23.833694

In [36]:
titanic.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,surname,prefix
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1,Allen,Miss
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1,Allison,Master
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0,Allison,Miss
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0,Allison,Mr
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0,Allison,Mrs

In [ ]:
titanic.info()

titanic['ticket']=titanic['ticket']

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   str
 2   sex       1309 non-null   str
 3   age       1046 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   str
 7   fare      1308 non-null   float64
 8   cabin     295 non-null    str
 9   embarked  1307 non-null   str
 10  survived  1309 non-null   int64
 11  surname   1309 non-null   object
 12  prefix    1309 non-null   str
dtypes: float64(2), int64(4), object(1), str(6)
memory usage: 133.1+ KB

In [39]:
titanic.pivot_table(values=['age','sibsp','fare'],
                    index='sex',
                    aggfunc=['mean','max','sum','median'])

             mean                        max                         sum  \
              age       fare     sibsp   age      fare sibsp         age
sex
female  28.687071  46.198097  0.652361  76.0  512.3292     8  11130.5834
male    30.585233  26.154601  0.413998  80.0  512.3292     8  20125.0833

                         median
              fare sibsp    age     fare sibsp
sex
female  21528.3130   304   27.0  23.0000   0.0
male    22022.1739   349   28.0  11.8875   0.0

In [40]:
# It is used to convert the datatype of the date column.
# pd.to_datetime(var['col_name'])

In [41]:
amazon=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv',encoding='ISO-8859-1')

In [43]:
amazon.head()

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002

In [44]:
pd.to_datetime(amazon['encontro'])

0      1998-01-01
1      1999-01-01
2      2000-01-01
3      2001-01-01
4      2002-01-01
          ...
6449   2012-01-01
6450   2013-01-01
6451   2014-01-01
6452   2015-01-01
6453   2016-01-01
Name: encontro, Length: 6454, dtype: datetime64[us]

In [ ]:
# date_range():
# It will create Dates between specified ranges.

# syntax: 
# pd.date_range(start='DD/MM/YYYY',
#               end='DD/MM/YYYY',
#               freq='char')

# w-week
# d=week
# B-business week
# MS-month start
# ME-month end
# YS-Year Start
# YE- Year End

In [ ]:
pd.date_range(start='07/01/2000',
              end='31/05/2001',
              freq='')

DatetimeIndex(['2000-07-31', '2000-08-31', '2000-09-30', '2000-10-31',
               '2000-11-30', '2000-12-31', '2001-01-31', '2001-02-28',
               '2001-03-31', '2001-04-30', '2001-05-31'],
              dtype='datetime64[us]', freq='ME')