In [1]:
import pandas as pd

In [ ]:
# groupby for 2 columns

# Syntax: 
# var_1=var.groupby(['categorical_col_1','categorical_col_2'])

In [6]:
tips=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/tips.csv')

In [7]:
tips.head()

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4

In [8]:
tips['sex'].unique()

<StringArray>
['Female', 'Male']
Length: 2, dtype: str

In [9]:
tips['smoker'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [10]:
ge_smokers=tips.groupby(['sex','smoker'])

In [11]:
ge_smokers.groups

{('Female',
  'No'): Index([  0,   4,  11,  14,  16,  18,  21,  22,  29,  32,  33,  37,  51,  52,
         57,  66,  71,  74,  82,  85,  94, 104, 111, 114, 115, 117, 118, 119,
        121, 124, 125, 127, 128, 131, 132, 133, 134, 135, 136, 137, 139, 140,
        143, 144, 145, 146, 147, 155, 157, 158, 162, 223, 238, 243],
       dtype='int64'),
 ('Female',
  'Yes'): Index([ 67,  72,  73,  92,  93, 100, 101, 102, 103, 109, 164, 168, 169, 178,
        186, 188, 191, 197, 198, 201, 202, 203, 205, 209, 213, 214, 215, 219,
        221, 225, 226, 229, 240],
       dtype='int64'),
 ('Male',
  'No'): Index([  1,   2,   3,   5,   6,   7,   8,   9,  10,  12,  13,  15,  17,  19,
         20,  23,  24,  25,  26,  27,  28,  30,  31,  34,  35,  36,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  53,  54,  55,
         59,  64,  65,  68,  70,  75,  77,  78,  79,  81,  84,  86,  87,  88,
         89,  91,  99, 108, 110, 112, 113, 116, 120, 122, 123, 126, 129, 130,
        141, 142, 148, 149, 150, 151, 152, 153, 154, 156, 159, 160, 161, 163,
        165, 166, 167, 185, 195, 212, 227, 228, 232, 233, 235, 239, 242],
       dtype='int64'),
 ('Male',
  'Yes'): Index([ 56,  58,  60,  61,  62,  63,  69,  76,  80,  83,  90,  95,  96,  97,
         98, 105, 106, 107, 138, 170, 171, 172, 173, 174, 175, 176, 177, 179,
        180, 181, 182, 183, 184, 187, 189, 190, 192, 193, 194, 196, 199, 200,
        204, 206, 207, 208, 210, 211, 216, 217, 218, 220, 222, 224, 230, 231,
        234, 236, 237, 241],
       dtype='int64')}

In [14]:
female_smoker=ge_smokers.get_group(('Female','Yes'))

In [15]:
male_smoker=ge_smokers.get_group(('Male','Yes'))

In [16]:
female_not_smoker=ge_smokers.get_group(('Female','No'))

In [17]:
male_not_smoker=ge_smokers.get_group(('Male','No'))

In [28]:
female_smoker['sex'].count()

np.int64(33)

In [27]:
male_smoker['sex'].count()

np.int64(60)

In [26]:
female_not_smoker['sex'].count()

np.int64(54)

In [ ]:
male_not_smoker['sex'].count()

np.int64(97)

In [29]:
hr=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')

In [30]:
hr['department'].unique()

<StringArray>
[      'sales',  'accounting',          'hr',   'technical',     'support',
  'management',          'IT', 'product_mng',   'marketing',       'RandD']
Length: 10, dtype: str

In [31]:
hr['salary'].unique()

<StringArray>
['low', 'medium', 'high']
Length: 3, dtype: str

In [46]:
ge_hr=hr.groupby(['department','salary'])

In [33]:
emp_it=ge_hr.get_group(('IT','high'))

In [ ]:
emp_it['employee_id'].count()

np.int64(83)

In [40]:
hr.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [47]:
emp_sales=ge_hr.get_group(('sales','low'))

In [48]:
emp_sales['number_project'].mean()

np.float64(3.7579799904716533)

In [49]:
male_not_smoker['tip'].mean()

np.float64(3.11340206185567)

In [50]:
tips.head()

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4

In [63]:
male=tips.groupby(['time','sex'])

In [64]:
male_dinner=male.get_group(('Dinner','Male'))

In [65]:
male_dinner['Unnamed: 0'].count()

np.int64(124)

In [76]:
ge_tips=tips.groupby(['day'])

In [77]:
sunday_tip=ge_tips.get_group(('Sun',))

In [79]:
sunday_tip['tip'].sum()

np.float64(247.39000000000001)

In [80]:
wine_quality=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/winequalityN.csv')

In [81]:
wine_quality.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [85]:
ge_wine=wine_quality.groupby(['type'])

In [86]:
ph_white=ge_wine.get_group(('white',))

In [87]:
ph_white['pH'].count()

np.int64(4891)

In [ ]:
# Concatenation of DataFrames
# It is a process of merging two or more DataFrames,
# Syntax:
# 1) Vertical-> row by row
        # pd.concat([var1,var2...var n])
# Horizontal-> column by column
        # pd.concat([var1,var2...var n],axis=1)

In [ ]:
d={'ENAME':['SMITH','ALLEN','WARD','JONES','MARTIN'],
   'Eid':  [,7499,7521,7566,7698],
   'Salary':['8LPA','10LPA','9LPA','12LPA','15LPA']}

In [96]:
df=pd.DataFrame(d)

In [97]:
df

    ENAME   Eid Salary
0   SMITH  7369   8LPA
1   ALLEN  7499  10LPA
2    WARD  7521   9LPA
3   JONES  7566  12LPA
4  MARTIN  7698  15LPA

In [91]:
e={'STUDENT_ID':['01','02','03','04','05'],
   'STUDENT_NAME':['SMITH','ALLEN','WARD','JONES','MARTIN'],
   'STUDENT_COURSE':['BTECH','BSC','BA','LLB','MTECH']}

In [92]:
ef=pd.DataFrame(e)

In [94]:
ef

  STUDENT_ID STUDENT_NAME STUDENT_COURSE
0         01        SMITH          BTECH
1         02        ALLEN            BSC
2         03         WARD             BA
3         04        JONES            LLB
4         05       MARTIN          MTECH

In [99]:
pd.concat([df,ef])

    ENAME     Eid Salary STUDENT_ID STUDENT_NAME STUDENT_COURSE
0   SMITH  7369.0   8LPA        NaN          NaN            NaN
1   ALLEN  7499.0  10LPA        NaN          NaN            NaN
2    WARD  7521.0   9LPA        NaN          NaN            NaN
3   JONES  7566.0  12LPA        NaN          NaN            NaN
4  MARTIN  7698.0  15LPA        NaN          NaN            NaN
0     NaN     NaN    NaN         01        SMITH          BTECH
1     NaN     NaN    NaN         02        ALLEN            BSC
2     NaN     NaN    NaN         03         WARD             BA
3     NaN     NaN    NaN         04        JONES            LLB
4     NaN     NaN    NaN         05       MARTIN          MTECH

In [100]:
pd.concat([df,ef],axis=1)

    ENAME   Eid Salary STUDENT_ID STUDENT_NAME STUDENT_COURSE
0   SMITH  7369   8LPA         01        SMITH          BTECH
1   ALLEN  7499  10LPA         02        ALLEN            BSC
2    WARD  7521   9LPA         03         WARD             BA
3   JONES  7566  12LPA         04        JONES            LLB
4  MARTIN  7698  15LPA         05       MARTIN          MTECH

In [101]:
# # Joins:
# When we want to fetch the data from 2 different
# DataFrames simultaneously we use joins.

# Types:
# 1) Right()
# 2) Left()-> 
# 3) inner()
# 4) outer()

# Syntax-> 
# pd.merge(var1,var2,on='common_col',how='inner/outer/left/right')

In [102]:
df_1=pd.DataFrame({'Blood_Group':['A-','B+','O-','A+'],
                   'Eid':[105,104,103,106],
                   'Bonus':['12K','3K','5K','9K']})

In [103]:
df_1

  Blood_Group  Eid Bonus
0          A-  105   12K
1          B+  104    3K
2          O-  103    5K
3          A+  106    9K

In [106]:
d={'ENAME':['SMITH','ALLEN','WARD','JONES'],
   'Eid':  [105,104,103,106],
   'Salary':['8LPA','10LPA','9LPA','12LPA']}

In [107]:
df=pd.DataFrame(d)

In [108]:
pd.merge(df,df_1,on='Eid',how='inner')

   ENAME  Eid Salary Blood_Group Bonus
0  SMITH  105   8LPA          A-   12K
1  ALLEN  104  10LPA          B+    3K
2   WARD  103   9LPA          O-    5K
3  JONES  106  12LPA          A+    9K

In [109]:
# Feature Engineering:-
# It is a process of creating new columns based on existing columns.
# syntax: 
# var['new_col']=value

In [110]:
titanic=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/titanic.csv'
'')

In [111]:
titanic.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [ ]:
titanic['family_count_without_Traveler']=titanic['sibsp']+titanic['parch']

In [115]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   pclass                         1309 non-null   int64
 1   name                           1309 non-null   str
 2   sex                            1309 non-null   str
 3   age                            1046 non-null   float64
 4   sibsp                          1309 non-null   int64
 5   parch                          1309 non-null   int64
 6   ticket                         1309 non-null   str
 7   fare                           1308 non-null   float64
 8   cabin                          295 non-null    str
 9   embarked                       1307 non-null   str
 10  survived                       1309 non-null   int64
 11  family_count_without_Traveler  1309 non-null   int64
dtypes: float64(2), int64(5), str(5)
memory usage: 122.8 KB

In [116]:
titanic['family_count_Traveler']=titanic['sibsp']+titanic['parch']+1

In [117]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   pclass                         1309 non-null   int64
 1   name                           1309 non-null   str
 2   sex                            1309 non-null   str
 3   age                            1046 non-null   float64
 4   sibsp                          1309 non-null   int64
 5   parch                          1309 non-null   int64
 6   ticket                         1309 non-null   str
 7   fare                           1308 non-null   float64
 8   cabin                          295 non-null    str
 9   embarked                       1307 non-null   str
 10  survived                       1309 non-null   int64
 11  family_count_without_Traveler  1309 non-null   int64
 12  family_count_Traveler          1309 non-null   int64
dtypes: float64(2), int64(6), str(5)
memory usage: 133.1 KB

In [120]:
l2=[]
for i in titanic['name']:
    n=i.split(',')[0]
    l2.append(n)
 
titanic['surname']=l2

In [122]:
titanic.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,family_count_without_Traveler,family_count_Traveler,surname
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1,0,1,Allen
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1,3,4,Allison
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0,3,4,Allison
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0,3,4,Allison
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0,3,4,Allison