In [1]:
import pandas as pd

In [2]:
hr=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')

In [3]:
hr.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [4]:
hr[hr['department']=='IT']['number_project'].mean()

np.float64(3.8166259168704157)

In [8]:
titanic=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/titanic.csv' \
'')
wine_quality=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/winequalityN.csv')

tips=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/tips.csv')

amazon=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv',encoding='ISO-8859-1')

hr=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')

In [9]:
titanic.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [11]:
titanic[(titanic['sex']=='female') & (titanic['survived']==1)]['age'].mean()

np.float64(29.81535410958904)

In [13]:
tips[(tips['sex']=="Female")]['tip'].max()

np.float64(6.5)

In [14]:
wine_quality.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [16]:
wine_quality[(wine_quality['type']=='red') ]['pH'].mean()

np.float64(3.3108641202254225)

In [17]:
amazon.head()

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002

In [18]:
amazon.info()

<class 'pandas.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ano       6454 non-null   int64
 1   mes       6454 non-null   str
 2   estado    6454 non-null   str
 3   numero    6322 non-null   str
 4   encontro  6454 non-null   str
dtypes: int64(1), str(4)
memory usage: 252.2 KB

In [19]:
tips.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  244 non-null    int64
 1   total_bill  244 non-null    float64
 2   tip         244 non-null    float64
 3   sex         244 non-null    str
 4   smoker      244 non-null    str
 5   day         244 non-null    str
 6   time        244 non-null    str
 7   size        244 non-null    int64
dtypes: float64(2), int64(2), str(4)
memory usage: 15.4 KB

In [20]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   str
 2   sex       1309 non-null   str
 3   age       1046 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   str
 7   fare      1308 non-null   float64
 8   cabin     295 non-null    str
 9   embarked  1307 non-null   str
 10  survived  1309 non-null   int64
dtypes: float64(2), int64(4), str(5)
memory usage: 112.6 KB

In [22]:
wine_quality.info()

<class 'pandas.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   type                  6497 non-null   str
 1   fixed acidity         6487 non-null   float64
 2   volatile acidity      6489 non-null   float64
 3   citric acid           6494 non-null   float64
 4   residual sugar        6495 non-null   float64
 5   chlorides             6495 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6488 non-null   float64
 10  sulphates             6493 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64
dtypes: float64(11), int64(1), str(1)
memory usage: 660.0 KB

In [23]:
titanic['cabin'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
1304     True
1305     True
1306     True
1307     True
1308     True
Name: cabin, Length: 1309, dtype: bool

In [29]:
wine_quality['sulphates'].isnull().sum()

np.int64(4)

In [30]:
amazon['numero'].isnull().sum()

np.int64(132)

In [32]:
titanic['age'].notnull().sum()

np.int64(1046)

In [33]:
# var['col_nme'].notnull()

In [36]:
d={'ano':'years','mes':'months','estado':'state','numero':'number of fires','encontro':'Date'}

amazon.rename(columns=d,inplace=True)

In [37]:
amazon.head()

   years   months state number of fires      Date
0   1998  Janeiro  Acre         0 Fires  1/1/1998
1   1999  Janeiro  Acre         0 Fires  1/1/1999
2   2000  Janeiro  Acre         0 Fires  1/1/2000
3   2001  Janeiro  Acre         0 Fires  1/1/2001
4   2002  Janeiro  Acre         0 Fires  1/1/2002

In [ ]:
# var.duplicated()-> It will return duplicated rows from the dataframe.

In [43]:
amazon.duplicated().sum()

np.int64(30)

In [ ]:
# var.drop_duplicates(inplace=true)-> It will remove duplicated rows from the dataframe.