In [1]:
import pandas as pd

In [2]:
titanic=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/titanic.csv' \
'')
wine_quality=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/winequalityN.csv')

tips=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/tips.csv')

amazon=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv',encoding='ISO-8859-1')

hr=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')

In [3]:
# var.drop_duplicates(inplace=true)
# It will delete the duplicate rows.

In [4]:
d={'ENAME':['SMITH','ALLEN','WARD','JONES','MARTIN','SMITH','CLARK','SCOTT','KING','TURNER'],
   'Eid':  [7369,7499,7521,7566,7698,7369,7788,7902,7934,7844],
   'Salary':['8LPA','10LPA','9LPA','12LPA','15LPA','8LPA','13LPA','16LPA','20LPA','11LPA']}

In [6]:
df=pd.DataFrame(d)

In [7]:
df

    ENAME   Eid Salary
0   SMITH  7369   8LPA
1   ALLEN  7499  10LPA
2    WARD  7521   9LPA
3   JONES  7566  12LPA
4  MARTIN  7698  15LPA
5   SMITH  7369   8LPA
6   CLARK  7788  13LPA
7   SCOTT  7902  16LPA
8    KING  7934  20LPA
9  TURNER  7844  11LPA

In [8]:
df.duplicated().sum()

np.int64(1)

In [9]:
wine_quality.duplicated().sum()

np.int64(1168)

In [12]:
wine_quality.shape

(6497, 13)

In [13]:
wine_quality.duplicated().sum()

np.int64(1168)

In [14]:
wine_quality.drop_duplicates(inplace=True)

In [15]:
wine_quality.shape

(5329, 13)

In [16]:
# changing the present in the column.
# var={'old_data':'new_data'}
# var_1['col_name']=var_1['col_name'].map(var)

# 1) When we want to change whole data present in the column we use map().

# 2) we can't change any particular data suing map() otherwise it will make all the value "Nan".

In [17]:
wine_quality.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
6,white,6.2,0.32,0.16,7.0,0.045,30.0,136.0,0.9949,3.18,0.47,9.6,6

In [19]:
wine_quality['type'].unique()

<StringArray>
['white', 'red']
Length: 2, dtype: str

In [20]:
d= {'white':'white_wine','red':'red_wine'}
wine_quality['type']=wine_quality['type'].map(d)

In [21]:
wine_quality.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white_wine,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white_wine,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white_wine,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white_wine,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
6,white_wine,6.2,0.32,0.16,7.0,0.045,30.0,136.0,0.9949,3.18,0.47,9.6,6

In [23]:
amazon.head()

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002

In [24]:
amazon['mes'].unique()

<StringArray>
[  'Janeiro', 'Fevereiro',     'Março',     'Abril',      'Maio',     'Junho',
     'Julho',    'Agosto',  'Setembro',   'Outubro',  'Novembro',  'Dezembro']
Length: 12, dtype: str

In [25]:
d={'Janeiro':'january', 'Fevereiro':'february',     'Março':'march',     'Abril':'april',      'Maio':'may',     'Junho':'june',
     'Julho':'july',    'Agosto':'augest',  'Setembro':'september',   'Outubro':'october',  'Novembro':'novemeber',  'Dezembro':'december'}

In [26]:
amazon['mes']=amazon['mes'].map(d)

In [27]:
amazon['mes'].unique()

<StringArray>
[  'january',  'february',     'march',     'april',       'may',      'june',
      'july',    'augest', 'september',   'october', 'novemeber',  'december']
Length: 12, dtype: str